# Generated by Django 4.0.3 on 2022-03-29 11:23

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(validators=[user.models.DateValidator], verbose_name='Date of birth')),
                ('name', models.CharField(max_length=20,
                                          validators=[
                                              django.core.validators.MinLengthValidator(limit_value=2, message=None),
                                              user.models.CharValidator], verbose_name='Name')),
                ('last_name', models.CharField(max_length=20, validators=[
                    django.core.validators.MinLengthValidator(limit_value=2, message=None), user.models.CharValidator],
                                               verbose_name='Last name')),
                ('gender',
                 models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender')),
                ('cv', models.FileField(upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])],
                                        verbose_name='CV / Resume')),
                ('image', models.ImageField(upload_to='',
                                            validators=[django.core.validators.validate_image_file_extension,
                                                        django.core.validators.FileExtensionValidator(
                                                            allowed_extensions=['jpeg', 'png'])],
                                            verbose_name='Picture')),
            ],
        ),
    ]
